const crypto = require('crypto');

const ALGORITHM = 'aes-256-gcm';
const IV_LENGTH = 12; 

/**
 * Reads the key exactly as the Bubble plugin expects it.
 */
function getKey() {
  const secret = process.env.AES_ENCRYPTION_KEY;
  if (!secret) {
    throw new Error("AES_ENCRYPTION_KEY environment variable is missing.");
  }
  
  // Based on your screenshot, the key is a 64-character hex string.
  // 64 hex characters = exactly 32 bytes, which is what AES-256 requires.
  if (secret.length === 64 && /^[0-9a-fA-F]+$/.test(secret)) {
    return Buffer.from(secret, 'hex');
  }
  
  // Fallback: If you ever change it to a 32-character plain text string
  if (Buffer.byteLength(secret, 'utf8') === 32) {
    return Buffer.from(secret, 'utf8');
  }

  throw new Error("Invalid AES_ENCRYPTION_KEY length. To match the Bubble plugin, it must be a 64-character hex string or exactly 32 characters of plain text.");
}

/**
 * Encrypts a string using AES-256-GCM.
 * Returns: "iv:authTag:encryptedData" (Matches Bubble Plugin format)
 */
function encrypt(text) {
  if (!text) return text;

  const iv = crypto.randomBytes(IV_LENGTH);
  const cipher = crypto.createCipheriv(ALGORITHM, getKey(), iv);

  let encrypted = cipher.update(text, 'utf8', 'hex');
  encrypted += cipher.final('hex');
  
  const authTag = cipher.getAuthTag().toString('hex');

  return `${iv.toString('hex')}:${authTag}:${encrypted}`;
}

/**
 * Decrypts a string generated by the Bubble Plugin
 */
function decrypt(encryptedString) {
  if (!encryptedString) return encryptedString;

  const parts = encryptedString.split(':');
  if (parts.length !== 3) {
    throw new Error('Invalid encrypted text format. Expected iv:authTag:ciphertext');
  }

  const iv = Buffer.from(parts[0], 'hex');
  const authTag = Buffer.from(parts[1], 'hex');
  const encryptedText = parts[2];

  const decipher = crypto.createDecipheriv(ALGORITHM, getKey(), iv);
  decipher.setAuthTag(authTag);

  let decrypted = decipher.update(encryptedText, 'hex', 'utf8');
  decrypted += decipher.final('utf8');

  return decrypted;
}

module.exports = { encrypt, decrypt };
