const crypto = require('crypto');

const ALGORITHM = 'aes-256-gcm';
const IV_LENGTH = 12; 

function getKey() {
  const secret = process.env.AES_ENCRYPTION_KEY;
  if (!secret) {
    throw new Error("AES_ENCRYPTION_KEY environment variable is missing.");
  }
  
  // If the key is a valid hex string (like yours)
  if (/^[0-9a-fA-F]+$/.test(secret)) {
    // If it's longer than 64 hex characters (32 bytes), truncate it.
    // AES-256 strictly requires 32 bytes. Your 128-character string is 64 bytes,
    // so the Bubble plugin is likely just using the first 64 characters.
    const hexKey = secret.length > 64 ? secret.substring(0, 64) : secret;
    
    // Convert to buffer
    const keyBuffer = Buffer.from(hexKey, 'hex');
    
    // Ensure it is exactly 32 bytes before returning
    if (keyBuffer.length === 32) return keyBuffer;
  }
  
  // Fallback: If it's standard plain text, take the first 32 characters
  if (Buffer.byteLength(secret, 'utf8') >= 32) {
    return Buffer.from(secret.substring(0, 32), 'utf8');
  }

  // Last resort fallback: Hash it to force 32 bytes
  return crypto.createHash('sha256').update(String(secret)).digest();
}

/**
 * Encrypts a string using AES-256-GCM.
 * Returns: "iv:authTag:encryptedData"
 */
function encrypt(text) {
  if (!text) return text;

  const iv = crypto.randomBytes(IV_LENGTH);
  const cipher = crypto.createCipheriv(ALGORITHM, getKey(), iv);

  let encrypted = cipher.update(text, 'utf8', 'hex');
  encrypted += cipher.final('hex');
  
  const authTag = cipher.getAuthTag().toString('hex');

  return `${iv.toString('hex')}:${authTag}:${encrypted}`;
}

/**
 * Decrypts a string generated by the Bubble Plugin
 */
function decrypt(encryptedString) {
  if (!encryptedString) return encryptedString;

  const parts = encryptedString.split(':');
  if (parts.length !== 3) {
    throw new Error('Invalid encrypted text format. Expected iv:authTag:ciphertext');
  }

  const iv = Buffer.from(parts[0], 'hex');
  const authTag = Buffer.from(parts[1], 'hex');
  const encryptedText = parts[2];

  const decipher = crypto.createDecipheriv(ALGORITHM, getKey(), iv);
  decipher.setAuthTag(authTag);

  let decrypted = decipher.update(encryptedText, 'hex', 'utf8');
  decrypted += decipher.final('utf8');

  return decrypted;
}

module.exports = { encrypt, decrypt };
